# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# 04/12/2022 08:36 am - SSN - Manual

trigger:
- main

pool:
  name: ssn-self-hosted-pool-20210604


# 04/12/2022 08:36 am - SSN - Manual


variables: 
  RestoreBuildProjects_1: '**/*.csproj'
  project1: '.\ps_310_BethanysPieShopHRM.Api\ps_310_BethanysPieShopHRM.Api.csproj'
  project2: '.\ps_310_BethanysPieShopHRM.Client\ps_310_BethanysPieShopHRM.Client.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  WebAppName_api: ps-310-blazor-api-30210511
  WebAppName_web: PS-310-BethanysPieShopHRMApi20210512
#  connectedServiceName: 'Pay-As-You-Go (d6723a94-6723-4e85-b988-03bf28d6ea51)'
#  connectedServiceName: 'ssn-service-connection--default-web-centralus-20220321'
  connectedServiceName: 'Pay-As-You-Go(1)(d6723a94-6723-4e85-b988-03bf28d6ea51)'
  resourceGroupName: 'PS_310_Blazor'

steps:

- task: DotNetCoreCLI@2
  displayName: Restore 1
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects_1)'
  enabled: true

- task: DotNetCoreCLI@2
  displayName: 'Build projects $(project1)' 
  inputs:
    projects: '$(project1)'
    arguments: '--configuration $(BuildConfiguration)'
  enabled: true

- task: DotNetCoreCLI@2
  displayName: 'Build projects $(project2)' 
  inputs:
    projects: '$(project2)'
    arguments: '--configuration $(BuildConfiguration)'
  enabled: true

- task: DotNetCoreCLI@2
  displayName: 'Publish: all'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) '


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  enabled: false


- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy API: [$(WebAppName_api)]'
  inputs:
    azureSubscription: '$(connectedServiceName)'
    WebAppName: '$(WebAppName_api)'
    #DeployToSlotFlag: true
    ResourceGroupName: '$(resourceGroupName)'
    #SlotName: staging
    Package: '$(build.artifactstagingdirectory)/ps_310_BethanysPieShopHRM.Api.zip'
    TakeAppOfflineFlag: true

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Web: [$(WebAppName_web)]'
  inputs:
    azureSubscription: '$(connectedServiceName)'
    WebAppName: '$(WebAppName_web)'
    #DeployToSlotFlag: true
    ResourceGroupName: '$(resourceGroupName)'
    #SlotName: staging
    Package: '$(build.artifactstagingdirectory)/ps_310_BethanysPieShopHRM.client.zip'
    TakeAppOfflineFlag: false
    AdditionalArguments: ""
    UseWebDeploy: true
    DeploymentType: zipDeploy
    RemoveAdditionalFilesFlag: false
  enabled: true



# https://chrissainty.com/building-blazor-apps-using-azure-pipelines/


  

- task: DotNetCoreInstaller@1
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 5.0.407

- script: dotnet build --configuration $(buildconfiguration) $(project2)
  displayName: 'Build web app project $(project2)'
  enabled: false
 
- task: DotNetCoreCLI@2
  displayName: Publish app...
  inputs:
    command: publish
    publishWebProjects: true
    arguments: ' -- configuration $(BuildConfiguration) --output $(Build.ArticfactStagingDirectory) $(project2)'
    zipAfterPublish: false
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts...
  enabled: false
  




  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

  enabled: false

- task: AzureRmWebAppDeployment@3
  displayName: 'Deploy web: [$(WebAppName_web)]'
  inputs:
    azureSubscription: '$(connectedServiceName)'
    WebAppName: '$(WebAppName_web)'
    DeployToSlotFlag: true
    ResourceGroupName: '$(resourceGroupName)'
    #SlotName: staging
    Package: '$(build.artifactstagingdirectory)/ps_310_BethanysPieShopHRM.Client.zip'
  enabled: false

