# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# 04/12/2022 08:36 am - SSN - Manual

trigger:
- main

pool:
  name: ssn-self-hosted-pool-20210604


# 04/12/2022 08:36 am - SSN - Manual


variables: 
  RestoreBuildProjects: '**/*.csproj'
  projectNameRegEx: '**/ps_310.*(Client|app).csproj$'
  project1: 'ps_310_BethanysPieShopHRM.Api'
  project2: 'ps_310_BethanysPieShopHRM.Client'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  WebAppName_api: ps-310-blazor-api-30210511
  WebAppName_web: PS-310-BethanysPieShopHRMApi20210512
#  connectedServiceName: 'Pay-As-You-Go (d6723a94-6723-4e85-b988-03bf28d6ea51)'
  connectedServiceName: 'ssn-service-connection--default-web-centralus-20220321'
  resourceGroupName: 'PS_310_Blazor'

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'
  enabled: true

- task: DotNetCoreCLI@2
  displayName: Build all projects
  inputs:
    projects: '$(projectNameRegEx)'
    arguments: '--configuration $(BuildConfiguration)'
  enabled: true


- task: DotNetCoreCLI@2
  displayName: 'Publish: $(project1)'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) $(project1)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'


- task: AzureRmWebAppDeployment@3
  displayName: 'Deploy API: [$(WebAppName_api)]'
  inputs:
    azureSubscription: '$(connectedServiceName)'
    WebAppName: '$(WebAppName_api)'
    DeployToSlotFlag: true
    ResourceGroupName: '$(resourceGroupName)'
    SlotName: staging
    Package: '$(build.artifactstagingdirectory)/ColorWebsite.WebJob.zip'








- task: DotNetCoreCLI@2
  displayName: 'Publish: $(project2)'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) $(project2)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'


- task: AzureRmWebAppDeployment@3
  displayName: 'Deploy web: [$(WebAppName_web)]'
  inputs:
    azureSubscription: '$(connectedServiceName)'
    WebAppName: '$(WebAppName_web)'
    DeployToSlotFlag: true
    ResourceGroupName: '$(resourceGroupName)'
    SlotName: staging
    Package: '$(build.artifactstagingdirectory)/ColorWebsite.WebJob.zip'

